#!/bin/sh

mkdir -p /var/lib/partman

cat /proc/modules |
while read module_name x; do
	if [ "$module_name" = f2fs ]; then
		>/var/lib/partman/f2fs
		exit 0
	fi
done

if modprobe f2fs >/dev/null 2>/dev/null; then
	>/var/lib/partman/f2fs
	exit 0
fi

if grep -q f2fs /proc/filesystems; then
	>/var/lib/partman/f2fs
fi
